from __future__ import annotations

import importlib.metadata
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Callable, Mapping, Sequence


ROOT = Path(__file__).resolve().parents[1]
BUILD_INPUT = ROOT / "requirements-build.in"
BUILD_LOCK = ROOT / "requirements-build.lock"
RUNTIME_LOCK = ROOT / "requirements-runtime.lock"
EXPECTED_PIP_TOOLS_VERSION = "7.6.1"
CUSTOM_COMPILE_COMMAND = "python tools/compile_build_lock.py"
CANONICAL_INDEX = "https://pypi.org/simple"
CANONICAL_HEADER = (
    "#\n"
    "# This file is autogenerated by pip-compile with Python 3.11\n"
    "# by the following command:\n"
    "#\n"
    f"#    {CUSTOM_COMPILE_COMMAND}\n"
    "#\n"
).encode("utf-8")
COMPILE_ARGUMENTS = (
    "-m",
    "piptools",
    "compile",
    "--no-config",
    "--allow-unsafe",
    "--generate-hashes",
    f"--index-url={CANONICAL_INDEX}",
    "--output-file=requirements-build.lock",
    "--strip-extras",
    "requirements-build.in",
)

_SOURCE_PIN = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*(?:\[[A-Za-z0-9,._-]+\])?)"
    r"==(?P<version>[^\s;]+)"
    r"(?:\s+--hash=sha256:[0-9a-f]{64})*$"
)
_REQUIREMENT = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*(?:\[[A-Za-z0-9,._-]+\])?)"
    r"==(?P<version>[^\s\\;]+)(?:\s*\\)?$"
)
_SHA256 = re.compile(r"--hash=sha256:([0-9a-f]{64})(?=\s|\\|$)")
_WINDOWS_ABSOLUTE = re.compile(r"(?<![A-Za-z0-9+.-])[A-Za-z]:[\\/]")
_UNSAFE_WARNING = "WARNING: The following packages were not pinned"


def _normalized_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name.lower())


def _source_pip_version(payload: bytes) -> str:
    pins = _source_pins(payload, label="requirements-build.in")
    versions = tuple(version for name, version in pins.items() if name == "pip")
    if len(versions) != 1:
        raise SystemExit("requirements-build.in must contain one exact pip==... source pin")
    return versions[0]


def _source_pins(payload: bytes, *, label: str) -> dict[str, str]:
    try:
        lines = payload.decode("utf-8").splitlines()
    except UnicodeDecodeError as exc:
        raise SystemExit(f"{label} is not UTF-8") from exc
    pins: dict[str, str] = {}
    for line in lines:
        if not line or line.startswith("#") or line.startswith("-r "):
            continue
        match = _SOURCE_PIN.fullmatch(line)
        if match is None:
            raise SystemExit(f"{label} contains a non-exact source requirement")
        name = _normalized_name(match.group("name").split("[", 1)[0])
        if name in pins:
            raise SystemExit(f"{label} contains a duplicate source requirement: {name}")
        pins[name] = match.group("version")
    if not pins:
        raise SystemExit(f"{label} contains no exact source requirements")
    return pins


def _lock_stanzas(payload: bytes) -> dict[str, tuple[str, tuple[str, ...]]]:
    try:
        lines = payload.decode("utf-8").splitlines()
    except UnicodeDecodeError as exc:
        raise SystemExit("requirements-build.lock is not UTF-8") from exc
    stanzas: dict[str, tuple[str, tuple[str, ...]]] = {}
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line or line.startswith("#"):
            index += 1
            continue
        if line[0].isspace() or line.startswith("--"):
            raise SystemExit("requirements-build.lock contains an orphaned option or continuation")
        match = _REQUIREMENT.fullmatch(line)
        if match is None:
            raise SystemExit("requirements-build.lock contains a non-exact requirement")
        block = [line]
        index += 1
        while index < len(lines) and (not lines[index] or lines[index][0].isspace() or lines[index].startswith("#")):
            block.append(lines[index])
            index += 1
        block_text = "\n".join(block)
        hashes = tuple(_SHA256.findall(block_text))
        if not hashes or block_text.count("--hash=") != len(hashes):
            raise SystemExit("requirements-build.lock contains a non-SHA256 or unhashed requirement")
        name = _normalized_name(match.group("name").split("[", 1)[0])
        if name in stanzas:
            raise SystemExit(f"requirements-build.lock contains duplicate requirement: {name}")
        stanzas[name] = (match.group("version"), hashes)
    if not stanzas:
        raise SystemExit("requirements-build.lock contains no resolved requirements")
    return stanzas


def _validate_generated_lock(
    payload: bytes,
    *,
    source_payload: bytes,
    included_source_payloads: Sequence[bytes] = (),
    private_roots: Sequence[Path] = (),
) -> dict[str, tuple[str, tuple[str, ...]]]:
    if not payload.startswith(CANONICAL_HEADER):
        raise SystemExit("requirements-build.lock header is not the canonical wrapper command")
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise SystemExit("requirements-build.lock is not UTF-8") from exc
    forbidden = ("--no-index", "--find-links", _UNSAFE_WARNING)
    if any(token in text for token in forbidden):
        raise SystemExit("requirements-build.lock contains a forbidden option or unsafe warning")
    if _WINDOWS_ABSOLUTE.search(text):
        raise SystemExit("requirements-build.lock contains an absolute path")
    normalized_text = text.replace("\\", "/")
    for root in private_roots:
        root_text = str(root.resolve()).replace("\\", "/")
        if root_text and root_text in normalized_text:
            raise SystemExit("requirements-build.lock contains a private generation path")
    expected_pip = _source_pip_version(source_payload)
    stanzas = _lock_stanzas(payload)
    pip_stanza = stanzas.get("pip")
    if pip_stanza is None or pip_stanza[0] != expected_pip:
        raise SystemExit("requirements-build.lock pip stanza does not match the source pin")
    sources = (("requirements-build.in", source_payload),) + tuple(
        (f"included source {index}", included)
        for index, included in enumerate(included_source_payloads, start=1)
    )
    for label, source in sources:
        for name, version in _source_pins(source, label=label).items():
            if name not in stanzas or stanzas[name][0] != version:
                raise SystemExit(f"requirements-build.lock does not represent source pin: {name}")
    return stanzas


def _clean_compile_environment(
    source: Mapping[str, str],
    *,
    empty_config: Path,
) -> dict[str, str]:
    environment = {
        key: value
        for key, value in source.items()
        if not key.upper().startswith("PIP_") and key != "CUSTOM_COMPILE_COMMAND"
    }
    if source.get("PIP_USE_FEATURE") == "truststore":
        environment["PIP_USE_FEATURE"] = "truststore"
    environment["PIP_CONFIG_FILE"] = str(empty_config)
    environment["CUSTOM_COMPILE_COMMAND"] = CUSTOM_COMPILE_COMMAND
    return environment


def _require_tooling(
    *,
    argv: Sequence[str] | None = None,
    implementation: str | None = None,
    version_info: Sequence[int] | None = None,
    version_reader: Callable[[str], str] = importlib.metadata.version,
) -> None:
    actual_argv = tuple(sys.argv[1:] if argv is None else argv)
    if actual_argv:
        raise SystemExit("compile_build_lock.py accepts no arguments")
    actual_implementation = sys.implementation.name if implementation is None else implementation
    actual_version = sys.version_info if version_info is None else version_info
    if actual_implementation != "cpython" or tuple(actual_version[:3]) != (3, 11, 9):
        raise SystemExit("compile_build_lock.py requires CPython 3.11.9")
    try:
        pip_tools_version = version_reader("pip-tools")
    except importlib.metadata.PackageNotFoundError as exc:
        raise SystemExit("compile_build_lock.py requires pip-tools==7.6.1") from exc
    if pip_tools_version != EXPECTED_PIP_TOOLS_VERSION:
        raise SystemExit("compile_build_lock.py requires pip-tools==7.6.1")


def _atomic_replace(destination: Path, payload: bytes) -> None:
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            suffix=".pending",
            delete=False,
        ) as handle:
            temporary_path = Path(handle.name)
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, destination)
        temporary_path = None
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def _compile_build_lock(
    *,
    root: Path = ROOT,
    runner: Callable[..., object] = subprocess.run,
    environment: Mapping[str, str] | None = None,
) -> bytes:
    source_path = root / BUILD_INPUT.name
    lock_path = root / BUILD_LOCK.name
    runtime_path = root / RUNTIME_LOCK.name
    source_payload = source_path.read_bytes()
    current_lock = lock_path.read_bytes()
    runtime_payload = runtime_path.read_bytes()
    _source_pip_version(source_payload)

    with tempfile.TemporaryDirectory(prefix="locpipe-build-lock-") as directory:
        temporary_root = Path(directory)
        (temporary_root / BUILD_INPUT.name).write_bytes(source_payload)
        (temporary_root / RUNTIME_LOCK.name).write_bytes(runtime_payload)
        temporary_output = temporary_root / BUILD_LOCK.name
        temporary_output.write_bytes(current_lock)
        empty_config = temporary_root / "pip-empty.ini"
        empty_config.write_bytes(b"")
        child_environment = _clean_compile_environment(
            os.environ if environment is None else environment,
            empty_config=empty_config,
        )
        runner(
            (sys.executable, *COMPILE_ARGUMENTS),
            cwd=temporary_root,
            env=child_environment,
            check=True,
        )
        generated = temporary_output.read_bytes()
        _validate_generated_lock(
            generated,
            source_payload=source_payload,
            included_source_payloads=(runtime_payload,),
            private_roots=(root, temporary_root),
        )
    _atomic_replace(lock_path, generated)
    return generated


def main() -> int:
    _require_tooling()
    payload = _compile_build_lock()
    print(f"wrote {BUILD_LOCK.name}: {len(payload)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
